
`define XLEN 64             //cpu 位数
`define INST_LEN 32         //指令长度
`define IMM_LEN 64          //立即数长度
`define REG_NUM 32          //寄存器个数
`define REG_ADDRWIDTH 5     //寄存器地址宽度
`define PC_RESET_ADDR `XLEN'h0000000080000000


/* csr */
`define CSR_REG_ADDRWIDTH 12     //寄存器地址宽度

//--------------------------------------------------------------------
// CSR Registers
//--------------------------------------------------------------------
`define CSR_MVENDORID `CSR_REG_ADDRWIDTH'hf11
`define CSR_MARCHID `CSR_REG_ADDRWIDTH'hf12
`define CSR_MIMPID `CSR_REG_ADDRWIDTH'hf13
`define CSR_MHARTID `CSR_REG_ADDRWIDTH'hf14
`define CSR_MCONFIGPTR `CSR_REG_ADDRWIDTH'hf15
//MACHINE TRAP SETUP
`define CSR_MSTATUS `CSR_REG_ADDRWIDTH'h300
`define CSR_MISA `CSR_REG_ADDRWIDTH'h301
`define CSR_MEDELEG `CSR_REG_ADDRWIDTH'h302
`define CSR_MIDELEG `CSR_REG_ADDRWIDTH'h303
`define CSR_MIE `CSR_REG_ADDRWIDTH'h304
`define CSR_MTVEC `CSR_REG_ADDRWIDTH'h305
`define CSR_MCOUNTEREN `CSR_REG_ADDRWIDTH'h306
//MACHINE TRAP HANDLING
`define CSR_MSCRATCH `CSR_REG_ADDRWIDTH'h340
`define CSR_MEPC `CSR_REG_ADDRWIDTH'h341
`define CSR_MCAUSE `CSR_REG_ADDRWIDTH'h342
`define CSR_MTVAL `CSR_REG_ADDRWIDTH'h343
`define CSR_MIP `CSR_REG_ADDRWIDTH'h344
`define CSR_MTINST `CSR_REG_ADDRWIDTH'h34a
`define CSR_MTVAL2 `CSR_REG_ADDRWIDTH'h34b
//MACHINE CONFIGURATION
`define CSR_MENVCFG `CSR_REG_ADDRWIDTH'h30a
`define CSR_MSECCFG `CSR_REG_ADDRWIDTH'h747



/* exc 操作码 */
`define EXCOP_LEN 5

`define EXCOP_NONE `EXCOP_LEN'd0
`define EXCOP_AUIPC `EXCOP_LEN'd1
`define EXCOP_LUI `EXCOP_LEN'd2
`define EXCOP_JAL `EXCOP_LEN'd3
`define EXCOP_JALR `EXCOP_LEN'd4
`define EXCOP_LOAD `EXCOP_LEN'd5
`define EXCOP_STORE `EXCOP_LEN'd6
`define EXCOP_BRANCH `EXCOP_LEN'd7
`define EXCOP_OPIMM `EXCOP_LEN'd8
`define EXCOP_OPIMM32 `EXCOP_LEN'd9
`define EXCOP_OP `EXCOP_LEN'd10
`define EXCOP_OP32 `EXCOP_LEN'd11

`define EXCOP_EBREAK `EXCOP_LEN'd12


/* ALU 操作码 */
`define ALUOP_LEN 6

`define ALUOP_NONE `ALUOP_LEN'd0
`define ALUOP_ADD `ALUOP_LEN'd1
`define ALUOP_SUB `ALUOP_LEN'd2
/* 逻辑操作 */
`define ALUOP_XOR `ALUOP_LEN'd3
`define ALUOP_OR `ALUOP_LEN'd4
`define ALUOP_AND `ALUOP_LEN'd5
/* 移位操作 */
`define ALUOP_SLL `ALUOP_LEN'd6
`define ALUOP_SRL `ALUOP_LEN'd7
`define ALUOP_SRA `ALUOP_LEN'd8
//忽略高32位的移位操作
`define ALUOP_SLLW `ALUOP_LEN'd9
`define ALUOP_SRLW `ALUOP_LEN'd10
`define ALUOP_SRAW `ALUOP_LEN'd11
/* 比较操作 */
`define ALUOP_SLT `ALUOP_LEN'd12
`define ALUOP_SLTU `ALUOP_LEN'd13

`define ALUOP_BEQ `ALUOP_LEN'd14
`define ALUOP_BNE `ALUOP_LEN'd15
`define ALUOP_BLT `ALUOP_LEN'd16
`define ALUOP_BGE `ALUOP_LEN'd17
`define ALUOP_BLTU `ALUOP_LEN'd18
`define ALUOP_BGEU `ALUOP_LEN'd19

/* 乘除法 */
`define ALUOP_MUL `ALUOP_LEN'd20
`define ALUOP_MULH `ALUOP_LEN'd21
`define ALUOP_MULHSU `ALUOP_LEN'd22
`define ALUOP_MULHU `ALUOP_LEN'd23
`define ALUOP_MULW `ALUOP_LEN'd24

`define ALUOP_DIV `ALUOP_LEN'd25
`define ALUOP_DIVU `ALUOP_LEN'd26
`define ALUOP_REM `ALUOP_LEN'd27
`define ALUOP_REMU `ALUOP_LEN'd28
`define ALUOP_DIVW `ALUOP_LEN'd29
`define ALUOP_DIVUW `ALUOP_LEN'd30
`define ALUOP_REMW `ALUOP_LEN'd31
`define ALUOP_REMUW `ALUOP_LEN'd32

/* mem操作码 */
`define MEMOP_LEN 4

/* 读取 */

`define MEMOP_NONE `MEMOP_LEN'd0 //空操作

`define MEMOP_LB `MEMOP_LEN'd1
`define MEMOP_LH `MEMOP_LEN'd2
`define MEMOP_LW `MEMOP_LEN'd3
`define MEMOP_LBU `MEMOP_LEN'd4
`define MEMOP_LHU `MEMOP_LEN'd5
`define MEMOP_LD `MEMOP_LEN'd6
`define MEMOP_LWU `MEMOP_LEN'd7

/* 写入 */
`define MEMOP_SB `MEMOP_LEN'd8
`define MEMOP_SH `MEMOP_LEN'd9
`define MEMOP_SW `MEMOP_LEN'd10
`define MEMOP_SD `MEMOP_LEN'd11


/* writeback 操作码 */
`define WBOP_LEN 4

/* 读取 */
`define WBOP_RD `WBOP_LEN'd0
`define WBOP_NONE `WBOP_LEN'd1

/* PC操作码 */
`define PCOP_LEN 3

`define PCOP_NONE `PCOP_LEN'd0 //空操作
`define PCOP_BRANCH `PCOP_LEN'd1
`define PCOP_JAL `PCOP_LEN'd2
`define PCOP_JALR `PCOP_LEN'd3
`define PCOP_INC4 `PCOP_LEN'd4





